/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import bibliothek.gui.DockController;
import bibliothek.gui.dock.DefaultDockable;
import bibliothek.gui.dock.SplitDockStation;
 import bibliothek.gui.dock.station.split.SplitDockGrid;
import book.PlainRedCube;
import com.jogamp.opengl.awt.GLCanvas;
import com.jogamp.opengl.util.Animator;
import components.ControladorDeEscena;
import components.Objects;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTextArea;
import mampos.Utils;
import rendering.Planta;
import rendering.ProjectionSpace;
import rendering.Room;


/**
 *
 * @author Diego
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    private GLCanvas myCanvas;
    private GLCanvas myCanvas2;
    public static JPopupMenu herramientas;
    
    private Planta floorSpace;
    
    public void iniciarMenu(){
        
        JList listaNombres=new JList();
        DefaultListModel modelo = new DefaultListModel();
        modelo.addElement("Elemento1");
        modelo.addElement("Elemento2");
        modelo.addElement("Elemento3");
        listaNombres.setModel(modelo);
        
    }
    
    public MainFrame() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        

        
        
        /*Room room = new Room();
        room.setMyCanvas(new GLCanvas());
        myCanvas = room.getMyCanvas();
        myCanvas.setBounds(0, 0, 600, 600);*/
        
        floorSpace = new Planta();
        floorSpace.setDimension(-10f, 10f, 10f, -10f);
        ControladorDeEscena.setDimension(-10f, 10f, 10f, -10f);
        
        myCanvas = floorSpace.myCanvas;
        floor.add(myCanvas);
        
        Animator animtr = new Animator(myCanvas);
        animtr.start();
        
       /* 
        ProjectionSpace projectionSpace = new ProjectionSpace();	
        myCanvas2 = projectionSpace.myCanvas2;
        jPanel2.add(myCanvas2);
        
        Animator animtr2 = new Animator(myCanvas2);
        animtr2.start();*/
       
        ProjectionSpace plainRedCube = new ProjectionSpace();	
        myCanvas2 = plainRedCube.myCanvas2;
        jPanel2.add(myCanvas2);
        
        Animator animtr2 = new Animator(myCanvas2);
        animtr2.start();
        
        components.Objects.currentStory = Objects.stories.get(0);
        
        currentLevel.setText("Nivel: " + components.Objects.currentStory.name);
        
    }

    
    public static void popup(){
        herramientas = new JPopupMenu();
        JTextArea escribir = new JTextArea();
        herramientas.add(escribir);
        JMenuItem muro = new JMenuItem("Muro");
        herramientas.add(muro);
        JMenuItem losa = new JMenuItem("Losa");
        herramientas.add(losa);
        herramientas.show(floor, (int)ControladorDeEscena.xScreen + 20, (int)ControladorDeEscena.yScreen + 20);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolsPopupMenu = new javax.swing.JPopupMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        currentLevel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        left = new javax.swing.JTextField();
        right = new javax.swing.JTextField();
        top = new javax.swing.JTextField();
        bottom = new javax.swing.JTextField();
        unitsButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        floor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        toolsPopupMenu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jToolBar1.setToolTipText("Sigue en orden");
        jToolBar1.setAlignmentX(0.0F);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setDoubleBuffered(true);
        jToolBar1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jButton1.setText("Niveles");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        currentLevel.setText("Nivel: 1");
        jToolBar1.add(currentLevel);

        jButton2.setText("Bajar nivel");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Subir nivel");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("Actualizar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        left.setText("-4");
        jToolBar1.add(left);

        right.setText("4");
        jToolBar1.add(right);

        top.setText("4");
        jToolBar1.add(top);

        bottom.setText("-4");
        jToolBar1.add(bottom);

        unitsButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        unitsButton.setText("Unidades");
        unitsButton.setFocusable(false);
        unitsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unitsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        unitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitsButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(unitsButton);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jSplitPane1.setDoubleBuffered(true);

        floor.setPreferredSize(new java.awt.Dimension(809, 457));
        floor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                floorMouseMoved(evt);
            }
        });
        floor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                floorPropertyChange(evt);
            }
        });
        floor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                floorKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout floorLayout = new javax.swing.GroupLayout(floor);
        floor.setLayout(floorLayout);
        floorLayout.setHorizontalGroup(
            floorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        floorLayout.setVerticalGroup(
            floorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(floor);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(318, 318, 318))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(800, 800, 800)
                .addComponent(jButton5)
                .addGap(209, 209, 209))
        );

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        fileMenu.setText("Archivo");

        loadMenuItem.setText("Cargar");
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadMenuItem);

        jMenuBar1.add(fileMenu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        mampos.Command.handleKey(evt);
        popup();
    }//GEN-LAST:event_formKeyPressed

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("presionado");
        try {
            mampos.Utils.loadToGson();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadMenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mampos.Command.openStoryEditor();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int indexOfCurrentStory = components.Objects.stories.indexOf(components.Objects.currentStory);
        if(indexOfCurrentStory == components.Objects.stories.size() - 1){
            components.Objects.currentStory = components.Objects.stories.get(0);
        } else {
            components.Objects.currentStory = components.Objects.stories.get(indexOfCurrentStory + 1);
        }
        currentLevel.setText("Nivel: " + components.Objects.currentStory.name); 
        floorSpace.vMat.identity();
        floorSpace.vMat.translate(0.0f, 0.0f, -components.Objects.currentStory.lowerStoryHeight - 0.1f);
        floorSpace.vMat.rotate(6*(float) (Math.PI/12),1.0f,0.0f,0.0f);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int indexOfCurrentStory = components.Objects.stories.indexOf(components.Objects.currentStory);
        if(indexOfCurrentStory == 0){
            components.Objects.currentStory = components.Objects.stories.get(components.Objects.stories.size() - 1);
        } else {
            components.Objects.currentStory = components.Objects.stories.get(indexOfCurrentStory - 1);
        }
        currentLevel.setText("Nivel: " + components.Objects.currentStory.name); 
        floorSpace.vMat.identity();
        floorSpace.vMat.translate(0.0f, 0.0f, -components.Objects.currentStory.lowerStoryHeight - 0.1f);
        floorSpace.vMat.rotate(6*(float) (Math.PI/12),1.0f,0.0f,0.0f);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        floorSpace.setDimension(Float.parseFloat(left.getText()),
                                Float.parseFloat(right.getText()),
                                Float.parseFloat(top.getText()),
                                Float.parseFloat(bottom.getText()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void floorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorMouseMoved
        // TODO add your handling code here:
      
    }//GEN-LAST:event_floorMouseMoved

    private void floorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_floorPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_floorPropertyChange

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFrame cuadrito = new JFrame();
        cuadrito.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Utils.abrirPDF("pdfs/agi.pdf", cuadrito);
        cuadrito.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void floorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_floorKeyPressed
        // TODO add your handling code here:
        popup();
    }//GEN-LAST:event_floorKeyPressed

    private void unitsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitsButtonActionPerformed
        // TODO add your handling code here:
        mampos.Command.openUnitsEditor();
    }//GEN-LAST:event_unitsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bottom;
    private javax.swing.JLabel currentLevel;
    private javax.swing.JMenu fileMenu;
    public static javax.swing.JPanel floor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField left;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JTextField right;
    private javax.swing.JPopupMenu toolsPopupMenu;
    private javax.swing.JTextField top;
    private javax.swing.JButton unitsButton;
    // End of variables declaration//GEN-END:variables
}
